services:
  - type: web
    name: aqi-dhanbad-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: OWM_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: RUN_SCHEDULER
        value: "true"
